#!/bin/bash -e

# Activation script that simply echos the service thats being activated or deactivated

case "$1" in
    activate)
        echo "Echo activation script: Activate service: $2"
        ;;
    deactivate)
        echo "Echo activation script: Deactivate service: $2"
	;;
    lock)
        echo "Echo activation script: Lock service: $2"
        ;;
    unlock)
        echo "Echo activation script: Unlock service: $2"
        ;;
esac

# Print the environment variables

echo "Environment variables:"
set
