#!/bin/bash
set -e
set -o pipefail

# Module that activates a NixOS system derivation, which makes it possible to
# upgrade NixOS.
#
# Container properties (environment variables):
# disableNixOSSystemProfile: Do not switch the system profile, but do activate
#     the configuration
# testNixOS: If set to true, it only tests the configuration and does not update
#     the bootloader

if [ "$testNixOS" = "" ]
then
    action="switch"
else
    action="test"
fi

case "$1" in
    activate)
        if [ "$disableNixOSSystemProfile" = "" ]
        then
            nix-env -p /nix/var/nix/profiles/system --set $2
            /nix/var/nix/profiles/system/bin/switch-to-configuration $action
        else
            $2/bin/switch-to-configuration $action
        fi
        ;;
    deactivate)
        if [ "$disableNixOSSystemProfile" = "" ]
        then
            nix-env -p /nix/var/nix/profiles/system --rollback
            /nix/var/nix/profiles/system/bin/switch-to-configuration $action
        fi
        ;;
esac
