#!/bin/bash
set -e
set -o pipefail

# Activation script that activates the given system derivation,
# which makes it possible to remotely upgrade NixOS

if [ "$testNixOS" = "" ]
then
    action="switch"
else
    action="test"
fi

case "$1" in
    activate)
        if [ "$disableNixOSSystemProfile" = "" ]
        then
            nix-env -p /nix/var/nix/profiles/system --set $2
            /nix/var/nix/profiles/system/bin/switch-to-configuration $action
        else
            $2/bin/switch-to-configuration $action
        fi
        ;;
    deactivate)
        if [ "$disableNixOSSystemProfile" = "" ]
        then
            nix-env -p /nix/var/nix/profiles/system --rollback
            /nix/var/nix/profiles/system/bin/switch-to-configuration $action
        fi
        ;;
esac
