#!/bin/bash -e

serviceName=$(basename $2)

# Systemd activation
case "$1" in
    activate)
        ( echo "[Unit]"
          echo "Description=$serviceName"
          echo
          echo "[Service]"
          echo "Environment=PATH=/run/current-system/sw/bin"
          echo "ExecStart=$(echo $2/bin/*)"
          echo "Restart=always"
          
          if [ -f $2/systemd-config ]
          then
              cat $2/systemd-config
          fi
        ) > /run/systemd/system/disnix-$serviceName.service
        
        systemctl --system daemon-reload
        systemctl start disnix-$serviceName.service
        ;;
    
    deactivate)
        systemctl stop disnix-$serviceName.service
        rm /run/systemd/system/disnix-$serviceName.service
        systemctl --system daemon-reload
        ;;
esac
