#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

target="$1/dysnomia-support/users"

if [ -d "$target" ]
then
    ls $target/* | while read userfile
    do
        username="$(basename "$userfile")"

        if pw user show "$username" > /dev/null
        then
            pw user del "$username"
        fi
    done
fi
