#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

deleteUser()
{
    local userfile="$1"
    username="$(basename "$userfile")"

    if id -u "$username"
    then
        userdel "$username"
    fi
}

target="$1/dysnomia-support/users"

if [ -f "$1" ]
then
    deleteUser "$1"
elif [ -d "$target" ]
then
    ls $target/* | while read userfile
    do
        deleteUser "$userfile"
    done
fi
