#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

deleteGroup()
{
    local groupfile="$1"
    group="$(basename "$groupfile")"

    if dscl . -read /Groups/$group
    then
        dscl . -delete /Groups/$group
    fi
}

target="$1/dysnomia-support/groups"

if [ -f "$1" ]
then
    deleteGroup "$1"
elif [ -d "$target" ]
then
    ls $target/* | while read groupfile
    do
        deleteGroup "$groupfile"
    done
fi
