#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

target="$1/dysnomia-support/groups"

if [ -d "$target" ]
then
    ls $target/* | while read groupfile
    do
        group="$(basename "$groupfile")"

        if dscl . -read /Groups/$group
        then
            dscl . -delete /Groups/$group
        fi
    done
fi
