#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

deleteUser()
{
    local userfile="$1"

    username="$(basename "$userfile")"

    if dscl . -read /Users/$username
    then
        if [ -n "$group" ]
        then
            dseditgroup -o edit -d "$username" -t user "$group"
        fi

        dscl . -delete /Users/$username
    fi
}

target="$1/dysnomia-support/users"

if [ -f "$1" ]
then
    deleteUser "$1"
elif [ -d "$target" ]
then
    ls $target/* | while read userfile
    do
        deleteUser "$userfile"
    done
fi
