#!/bin/bash -e

case "$1" in
    activate)
        echo "wrapper active" > /tmp/wrapper.state
        ;;
    deactivate)
        rm -f /tmp/wrapper.state
        ;;
    lock)
        if [ -f /tmp/wrapper.lock ]
        then
            exit 1
        else
            echo "1" > /tmp/wrapper.lock
        fi
        ;;
    unlock)
        rm -f /tmp/wrapper.lock
        ;;
esac
