#!/bin/bash -e

case "$1" in
    activate)
	# Initalize the given schema if the database does not exists
	componentName=`basename $2`
	dbName=${componentName:33}
	mysqlUsername=$3
	mysqlPassword=$4
	
	if [ "$(echo "show databases" | mysql -u root -N | grep -x $dbName)" = "" ]
	then
	    ( echo "create database $dbName;"
	      echo "use $dbName;"
	      cat $2/mysql-databases/*.sql ) | mysql --user=$mysqlUsername --password=$mysqlPassword -N
	fi
        ;;
    deactivate)
	# A MySQL database cannot be deactivated, we do not want to drop a database
	# with all data in it, right?
	echo
	;;
esac
