#!/bin/bash -e

# Activation script that activates the given system derivation,
# which makes it possible to remotely upgrade NixOS

if [ "$testNixOS" = "" ]
then
    action="switch"
else
    action="test"
fi

case "$1" in
    activate)
	if [ "$disableNixOSSystemProfile" = "" ]
	then
            nix-env -p /nix/var/nix/profiles/system --set $2
	fi
		
	$2/bin/switch-to-configuration $action
        ;;
    deactivate)
	if [ "$disableNixOSSystemProfile" = "" ]
        then
	    nix-env -p /nix/var/nix/profiles/system --rollback
	fi
	
        $2/bin/switch-to-configuration $action
	;;
esac
