#!/bin/bash -e

# Activation script that activates the given system derivation,
# which makes it possible to remotely upgrade NixOS

case "$1" in
    activate)
	if [ "$disableNixOSSystemProfile" = "" ]
	then
            nix-env -p /nix/var/nix/profiles/system --set $2
	fi
	
	$2/bin/switch-to-configuration switch
        ;;
    deactivate)
	if [ "$disableNixOSSystemProfile" = "" ]
        then
	    nix-env -p /nix/var/nix/profiles/system --rollback
	fi
	
        $2/bin/switch-to-configuration switch
	;;
esac
