#!/bin/bash -e

# Activation script that activates the given system derivation,
# which makes it possible to remotely upgrade NixOS

case "$1" in
    activate)
        nix-env -p /nix/var/nix/profiles/system --set $2
	$2/bin/switch-to-configuration switch
        ;;
    deactivate)
        nix-env -p /nix/var/nix/profiles/system --rollback
        $2/bin/switch-to-configuration switch
	;;
esac
