#!/bin/bash -e

catalinaBaseDir=/var/tomcat

case "$1" in
    activate)
	# Link all WAR files in the deployment directory, so that they will be activated with hot-deployment
	find $(readlink -f $2/webapps) -name \*.war | while read i
	do
	    # Link the web service
	    ln -sfn $i $catalinaBaseDir/webapps/`basename $i`
	    
	    # Link the configuration files if they exist
	    if [ -d $2/conf/Catalina ]
	    then
		mkdir -p $catalinaBaseDir/conf/Catalina/localhost
		
		for j in $2/conf/Catalina/*
		do
		    ln -sfn $j $catalinaBaseDir/conf/Catalina/localhost/`basename $j`
		done
	    fi
	done
	;;
    deactivate)
	# Remove AAR files from the deployment directory, so that they will be deactivated with hot deployment
	find $(readlink -f $2/webapps) -name \*.war | while read i
	do
	    # Remove the web service
	    rm -f $catalinaBaseDir/webapps/`basename $i`
	    
	    # Also remove the configuration files if they exist
	    if [ -d $2/conf/Catalina ]
	    then
	        for j in $2/conf/Catalina/*
		do
		    rm -f $catalinaBaseDir/conf/Catalina/localhost/`basename $j`
		done
	    fi
	done
	;;
esac
