#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

target="$1/dysnomia-support/users"

if [ -d "$target" ]
then
    ls $target/* | while read userfile
    do
        (
        source "$userfile"

        username="$(basename "$userfile")"

        if id -u "$username"
        then
            echo "User: $username already exists!" >&2

            actualUid="$(id -u $username)"
            if [ -n "$uid" ] && [ "$actualUid" != "$uid" ]
            then
                echo "$username already has uid: $actualUid, while: $uid was requested! Old uid will be retained!" >&2
            fi
        else
            (
            if [ -n "$uid" ]
            then
                echo "-u"
                echo "$uid"
            fi

            if [ -n "$password" ]
            then
                echo "-p"
                echo "$password"
            fi

            if [ -n "$group" ]
            then
                echo "-g"
                echo "$group"
            fi

            if [ -n "$description" ]
            then
                echo "-c"
                echo "$description"
            fi

            echo "-d"

            if [ -n "$homeDir" ]
            then
                echo "$homeDir"
            else
                echo "/dev/null"
            fi

            if [ -n "$shell" ]
            then
                echo "-s"
                echo "$shell"
            fi

            if [ "$createHomeDir" = "1" ]
            then
                echo "-m"
            fi

            echo "$username"
            ) | xargs -d '\n' useradd
        fi
    )
    done
fi
