#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

target="$1/dysnomia-support/groups"

if [ -d "$target" ]
then
    ls $target/* | while read groupfile
    do
        (
        source "$groupfile"

        group="$(basename "$groupfile")"

        if getent group $group
        then
            echo "Group: $group already exists!" >&2

            actualGid="$(getent group $group | cut -d: -f3)"
            if [ -n "$gid" ] && [ "$actualGid" != "$gid" ]
            then
                echo "$group already has uid: $actualGid, while: $gid was requested! Old gid will be retained!" >&2
            fi
        else
            (
            if [ -n "$gid" ]
            then
                echo "-g"
                echo "$gid"
            fi

            echo "$group"
            ) | xargs groupadd
        fi
        )
    done
fi
