#!/bin/bash
set -e
set -o pipefail
shopt -s nullglob

target="$1/dysnomia-support/groups"

if [ -d "$target" ]
then
    ls $target/* | while read groupfile
    do
        group="$(basename "$groupfile")"

        if getent group $group
        then
            groupdel "$group"
        fi
    done
fi
